# Generated by Django 2.0.5 on 2018-07-26 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=32, null=True)),
                ('password', models.CharField(max_length=64, null=True)),
                ('telephone', models.CharField(db_index=True, max_length=11, null=True)),
                ('email', models.CharField(db_index=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(db_index=True, max_length=16, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_level',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='background.UserLevel'),
        ),
    ]
