# Generated by Django 2.0.5 on 2018-07-29 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(db_index=True, max_length=100, null=True)),
                ('book_name', models.CharField(db_index=True, max_length=100, null=True)),
                ('author', models.CharField(db_index=True, max_length=100, null=True)),
                ('total_words', models.IntegerField(db_index=True, null=True)),
                ('category', models.CharField(db_index=True, max_length=100, null=True)),
                ('tags', models.CharField(db_index=True, max_length=100, null=True)),
                ('review_times', models.IntegerField(db_index=True, null=True)),
                ('click_times', models.IntegerField(db_index=True, null=True)),
                ('popularity', models.IntegerField(db_index=True, null=True)),
                ('read_times', models.IntegerField(db_index=True, null=True)),
                ('collection_times', models.IntegerField(db_index=True, null=True)),
                ('book_url', models.CharField(db_index=True, max_length=100, null=True)),
                ('image', models.CharField(db_index=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NovelSource',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('website', models.CharField(db_index=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='novelinfo',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='novel_search.NovelSource'),
        ),
    ]
