# Generated by Django 2.0.5 on 2018-07-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(db_index=True, max_length=100, null=True)),
                ('book_name', models.CharField(db_index=True, max_length=100, null=True)),
                ('author', models.CharField(db_index=True, max_length=100, null=True)),
                ('total_words', models.CharField(db_index=True, max_length=100, null=True)),
                ('category', models.CharField(db_index=True, max_length=100, null=True)),
                ('tags', models.CharField(db_index=True, max_length=100, null=True)),
                ('review_times', models.CharField(db_index=True, max_length=100, null=True)),
                ('click_times', models.CharField(db_index=True, max_length=100, null=True)),
                ('popularity', models.CharField(db_index=True, max_length=100, null=True)),
                ('read_times', models.CharField(db_index=True, max_length=100, null=True)),
                ('collection_times', models.CharField(db_index=True, max_length=100, null=True)),
                ('book_url', models.CharField(db_index=True, max_length=100, null=True)),
                ('image', models.CharField(db_index=True, max_length=100, null=True)),
            ],
        ),
    ]
